Foreground yes
User clamav
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
TCPSocket 3310
TCPAddr 0.0.0.0
StreamMaxLength 211M
MaxFileSize 200M
MaxScanSize 400M
MaxRecursion 20
MaxFiles 20000
ReadTimeout 300
CommandReadTimeout 30
SelfCheck 600
ScanArchive yes
ScanPDF yes
ScanOLE2 yes
ScanXMLDOCS yes
AlertEncrypted no
