"""Pure document-domain model."""

from bid_system.modules.documents.domain.elements import (
    BoundingBox,
    ComparisonInfo,
    ComparisonMatch,
    ComparisonOperator,
    ConfidenceBasis,
    ConfidenceStatus,
    DocumentElement,
    DocumentElementType,
    ElementConfidence,
    NormalizedBoundingBox,
    PagePosition,
    ParserProvenance,
    PictureElement,
    RecognitionConfidence,
    ReviewMetadata,
    ReviewStatus,
    TableCell,
    TableContinuation,
    TableElement,
    TableMergeStatus,
    TextElement,
    extract_comparison_symbols,
)
from bid_system.modules.documents.domain.models import (
    MAX_DOCUMENT_PAGES,
    Document,
    DocumentFormat,
    DocumentVersion,
)

__all__ = [
    "MAX_DOCUMENT_PAGES",
    "BoundingBox",
    "ComparisonInfo",
    "ComparisonMatch",
    "ComparisonOperator",
    "ConfidenceBasis",
    "ConfidenceStatus",
    "Document",
    "DocumentElement",
    "DocumentElementType",
    "DocumentFormat",
    "DocumentVersion",
    "ElementConfidence",
    "NormalizedBoundingBox",
    "PagePosition",
    "ParserProvenance",
    "PictureElement",
    "RecognitionConfidence",
    "ReviewMetadata",
    "ReviewStatus",
    "TableCell",
    "TableContinuation",
    "TableElement",
    "TableMergeStatus",
    "TextElement",
    "extract_comparison_symbols",
]
